### PR TITLE
Add git sha in docker image environment.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Inject git sha so we can use it here https://github.com/mozilla/lumbergh/blob/master/bin/run-prod.sh#L5

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@pmclanahan r?

**Comment by pmclanahan** [comment]
This looks good to me. A question I have just for my own info is: why is this better than just running something like:

```bash
echo $TRAVIS_COMMIT > static/revision.txt
```

from `.travis.yml`. I guess because other build systems could take advantage of the `$GIT_SHA` thing in the bootstrap script?

r+

**Comment by pmclanahan** [comment]
Also I think this is a better system than what we're using in basket. You agree?

**Comment by glogiotatidis** [comment]
> This looks good to me. A question I have just for my own info is: why is this better than just running something like:
> 
> echo $TRAVIS_COMMIT > static/revision.txt
> 
> from .travis.yml. I guess because other build systems could take advantage of the $GIT_SHA thing in the bootstrap script?

Yes and also static directory is generated within docker and if I'm not mistaken all its contents will be deleted when the collectstatic cmd runs.

**Comment by glogiotatidis** [comment]
> Also I think this is a better system than what we're using in basket. You agree?

Yap!

**Pull request merged**
